---
title: "GO Term Analysis For P7 cluster"
author: "Natalie Elphick"
date: "1/20/2022"
output: html_document
---


```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.width = 10,
                      fig.height = 8,
                      dev = "png", dpi = 400)
library(tidyverse)
library(Seurat)
library(kableExtra)
library(future)
library(clusterProfiler)
library(org.Mm.eg.db)
library(AnnotationHub)
plan()
plan("multicore", workers = 4,future.seed=TRUE)
set.seed(423)
```


```{r P7_GO,dev='png',dpi=400,cache=TRUE,fig.dim=c(12,10)}
###      Need to change this to a separate rmd     ###

sig.markers<-read_csv("sig_markers_1.csv")


# genes in the P7 clusters that have a log2 fold change >= 1
P7_genes_up  = sig.markers %>%
  filter(cluster ==7 & avg_log2FC >=1 & pct.1 >= .6) 



# Convert gene symbols to ENSEMBL
geneconvert_up = bitr(P7_genes_up$gene, fromType="SYMBOL", toType="ENSEMBL", OrgDb="org.Mm.eg.db")



# # Convert to MGI IDs
# mgi_ids <- select(org.Mm.eg.db, geneconvert$ENSEMBL, "MGI","ENSEMBL") %>% pull(MGI)
# 
# # Write MGI IDs for genewalk analysis
# mgi_ids %>% as_tibble() %>% write_delim(file = "P7_genes.txt",col_names = FALSE)

go_enrich_up <- enrichGO(gene = geneconvert_up$ENSEMBL,
                      OrgDb = org.Mm.eg.db,
                      keyType = "ENSEMBL",
                      pvalueCutoff = 0.01,
                      ont = "BP",pAdjustMethod = "fdr",readable = TRUE)



up_res <-go_enrich_up@result %>%
  as_tibble() %>%
  dplyr::select(Description,p.adjust,Count) %>%
  filter(p.adjust <0.01) %>%
  arrange(desc(Count)) %>%
  filter(Description != "RNA splicing, via transesterification reactions") %>%
  filter(Description != "RNA splicing, via transesterification reactions with bulged adenosine as nucleophile") %>%
  head(20)


up_res %>%
  ggplot(aes(y=reorder(Description,Count),x=Count))+
  geom_bar(stat = "identity",fill="#C70039")+
  ylab(label = "GO Term Description")+
  xlab(label = "# of Genes")+
  theme_light(base_size = 30)+
  theme(legend.position = "none",axis.text=element_text(color="black"))
```


