---
title: "Preprocessing Pipeline Comparison"
author: "Natalie Elphick, Laura Paez, Christina Zakarian"
date: "10/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(Seurat)
library(tidyverse)
library(ggpubr)
library(biomaRt)
```

```{r}
# Read in the samples.txt file 
samples = read_delim("samples.txt", delim="\n",col_names=FALSE) %>% pull(X1)

cr_total_cells = c()
cr_total_genes = c()
cr_med_gene_count = c()
cr_med_umi_count = c()

kb_total_cells = c()
kb_total_genes = c()
kb_med_gene_count = c()
kb_med_umi_count = c()

seurat_obj_cr = list()
seurat_obj_kb = list()

for (i in 1:length(samples)) {

  # Read in seurat objects
  seurat_obj_cr[[i]] = readRDS(paste0("cr_rds/sample_",samples[i],"_cr.rds"))
  seurat_obj_kb[[i]] = readRDS(paste0("kb_rds/sample_",samples[i],"_kb.rds"))
  
  # Pull total cell counts, total genes per cell, median genes and umis per cell
  cr_total_cells[i] = ncol(seurat_obj_cr[[i]]@assays[["RNA"]]@counts)
  cr_total_genes [i] = nrow(seurat_obj_cr[[i]]@assays[["RNA"]]@counts)

  cr_genes_per_cell = seurat_obj_cr[[i]]@meta.data$nFeature_RNA
  cr_umis_per_cell = seurat_obj_cr[[i]]@meta.data$nCount_RNA

  cr_med_gene_count[i] = median(cr_genes_per_cell)
  cr_med_umi_count[i] = median(cr_umis_per_cell)

  kb_total_cells[i] = ncol(seurat_obj_kb[[i]]@assays[["RNA"]]@counts)
  kb_total_genes [i] = nrow(seurat_obj_kb[[i]]@assays[["RNA"]]@counts)

  kb_genes_per_cell = seurat_obj_kb[[i]]@meta.data$nFeature_RNA
  kb_umis_per_cell = seurat_obj_kb[[i]]@meta.data$nCount_RNA

  kb_med_gene_count[i] = median(kb_genes_per_cell)
  kb_med_umi_count[i] = median(kb_umis_per_cell)
  
}
```

```{r}

# Read in timepoints from data provided by the Yu lab
timepoints = readxl::read_xlsx("Olfactory_Bulb_Summary.xlsx",sheet = 4) %>%
  rename_all(list(~make.names(.))) %>%
  separate(Sample.Name, sep = "-",into = c("Tissue","Timepoint")) %>%
  dplyr::select(Timepoint,Library.ID) %>%
  rename(Sample = Library.ID)


# Create tibbles from the ouputs of the loop
cr_df = tibble(Sample = samples,
               Pipeline = "CellRanger",
               Total_Cells = cr_total_cells,
               Total_Genes = cr_total_genes,
               Median_Gene_Count = cr_med_gene_count,
               Median_UMI_Count = cr_med_umi_count)

kb_df = tibble(Sample = samples,
               Pipeline = "Kallisto",
               Total_Cells = kb_total_cells,
               Total_Genes = kb_total_genes,
               Median_Gene_Count = kb_med_gene_count,
               Median_UMI_Count = kb_med_umi_count)

# Create a final results table for both pipelines and write the output
pipeline_comparison = cr_df %>%
  full_join(kb_df) %>%
  full_join(timepoints) %>%
  dplyr::select(Timepoint,Sample,everything()) %>%
  mutate(Timepoint = factor(Timepoint,
                            levels = c("E14","E18","P0","P3","P5","P7","P10","P14","P21","Adult"))) %>%
  arrange(Timepoint)


write_csv(pipeline_comparison,"pipeline_comparison.csv")

```

```{r}
total_cells = pipeline_comparison %>%
  ggplot(aes(x=Timepoint,y=Total_Cells,fill=Pipeline))+
  geom_bar(stat = "identity",position = "dodge")+
  ggtitle("Total Cells")+
  theme(plot.title = element_text(hjust = 0.5))

total_genes = pipeline_comparison %>%
  ggplot(aes(x=Timepoint,y=Total_Genes,fill=Pipeline))+
  geom_bar(stat = "identity",position = "dodge")+
  ggtitle("Total Genes")+
  theme(plot.title = element_text(hjust = 0.5))

med_gene_count = pipeline_comparison %>%
  ggplot(aes(x=Timepoint,y=Median_Gene_Count,fill=Pipeline))+
  geom_bar(stat = "identity",position = "dodge")+
  ggtitle("Median Gene Count")+
  theme(plot.title = element_text(hjust = 0.5))

med_umi_count = pipeline_comparison %>%
  ggplot(aes(x=Timepoint,y=Median_UMI_Count,fill=Pipeline))+
  geom_bar(stat = "identity",position = "dodge")+
  ggtitle("Median UMI Count")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, fig.dim=c(10,8)}
ggarrange(total_cells,total_genes,med_gene_count,med_umi_count,common.legend = TRUE)
```




```{r}
# Extract list of genes detected by cellranger, kallisto, and those only detected by either cellranger or kallisto 
genes_cr = list()
genes_kb = list()
genes_cr_only = list()
genes_kb_only = list()

for (i in 1:length(samples)) {
  genes_cr[[i]] = rownames(seurat_obj_cr[[i]]@assays[["RNA"]]@counts)
  genes_kb[[i]] = rownames(seurat_obj_kb[[i]]@assays[["RNA"]]@counts)
  genes_cr_only[[i]] = setdiff(genes_cr[[i]], genes_kb[[i]])
  genes_kb_only[[i]] = setdiff(genes_kb[[i]], genes_cr[[i]])
}

# Get set of genes that are present across all 10 samples for each group
genes_across_samples_cr = Reduce(intersect, genes_cr)
genes_across_samples_kb = Reduce(intersect, genes_kb)
genes_across_samples_cr_only = Reduce(intersect, genes_cr_only)
genes_across_samples_kb_only = Reduce(intersect, genes_kb_only)
```

```{r biomart}
# Select Ensembl BioMart database and dataset
ensembl <- useEnsembl(biomart = "genes", dataset = "mmusculus_gene_ensembl")

# Build biomaRt query with gene ID, gene name, and gene type
bm_query = getBM(attributes = c('ensembl_gene_id', 'external_gene_name', 'gene_biotype'), mart = ensembl)

# Create a tibble from the biomart query 
bm_tib = tibble(Gene_Name = bm_query$external_gene_name, Gene_ID = bm_query$ensembl_gene_id, Gene_Type = bm_query$gene_biotype)
```

```{r}
# Make tibbles for genes detected by cr, kb, and kb only with gene names, IDs, and types using biomart tibble
genes_cr_tib = inner_join(bm_tib, tibble(Gene_Name=genes_across_samples_cr)) 
genes_kb_tib = inner_join(bm_tib, tibble(Gene_Name=genes_across_samples_kb))
genes_cr_only_tib = inner_join(bm_tib, tibble(Gene_Name=genes_across_samples_cr_only))
genes_kb_only_tib = inner_join(bm_tib, tibble(Gene_Name=genes_across_samples_kb_only))
```

```{r}
# Get counts for gene types (protein coding, lncRNA, etc)
gene_type_count_cr = genes_cr_tib %>% group_by(Gene_Type) %>% summarize("count_cr" = n())
gene_type_count_kb = genes_kb_tib %>% group_by(Gene_Type) %>% summarize("count_kb" = n())
gene_type_count_cr_only = genes_cr_only_tib %>% group_by(Gene_Type) %>% summarize("count_cr_only" = n())
gene_type_count_kb_only = genes_kb_only_tib %>% group_by(Gene_Type) %>% summarize("count_kb_only" = n())

gene_type_count_tib = gene_type_count_cr %>%
  full_join(gene_type_count_kb) %>%
  full_join(gene_type_count_cr_only) %>%
  full_join(gene_type_count_kb_only)

```

# detected genes that dont have a gene name?
