---
title: "Violin Plots for Pre and Post Filtered Count Matrices"
author: "Natalie Elphick, Laura Paez, Christina Zakarian"
date: "11/17/2021"
output:  
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(Seurat)
library(tidyverse)
library(patchwork)
library(ggpubr)
```

```{r Read in Data}


labels = read_csv("../../data/timepoints.csv")
#samples = read_delim("../../data/samples.txt", delim="\n",col_names=FALSE) %>% pull(X1)

timepoints = labels$Timepoint
samples = labels$Sample
seurat_obj_kb = list()

for (i in 1:length(samples)) {

  # Read in seurat objects
  seurat_obj_kb[[i]] = readRDS(paste0("../../data/kb_rds/sample_",samples[i],"_kb.rds"))
  seurat_obj_kb[[i]]$sample <- samples[i]
  seurat_obj_kb[[i]]$timepoint <- timepoints[i]
  
}

```

```{r}

for (i in 1:length(seurat_obj_kb)){
  # Add percentage mitochondrial genes
  seurat_obj_kb[[i]][["percent.mt"]] <- PercentageFeatureSet(seurat_obj_kb[[i]], pattern = "^mt-")
  
  seurat_obj_kb[[i]]$timepoint <- timepoints[i]
  Idents(seurat_obj_kb[[i]]) <- "timepoint"
  
  # Print cell counts
  print(paste(timepoints[i],dim(seurat_obj_kb[[i]])[2]))

}

```

# Prefiltered

```{r,fig.width=11}
# Visualize QC metrics as a violin plots


ggarrange(VlnPlot(seurat_obj_kb[[1]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                  ncol = 3),VlnPlot(seurat_obj_kb[[2]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[3]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                  ncol = 3),VlnPlot(seurat_obj_kb[[4]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[5]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                  ncol = 3),VlnPlot(seurat_obj_kb[[6]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[7]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                  ncol = 3),VlnPlot(seurat_obj_kb[[8]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[9]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                  ncol = 3),VlnPlot(seurat_obj_kb[[10]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))
```

```{r}

# E14
seurat_obj_kb[[1]]<- subset(seurat_obj_kb[[1]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 12000 & percent.mt < 6)

# E18
seurat_obj_kb[[2]] <- subset(seurat_obj_kb[[2]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 6)

# P0
seurat_obj_kb[[3]] <- subset(seurat_obj_kb[[3]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 15000 & percent.mt < 9)

# P3
seurat_obj_kb[[4]] <- subset(seurat_obj_kb[[4]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 12000 & percent.mt < 7.5)

# P5
seurat_obj_kb[[5]] <- subset(seurat_obj_kb[[5]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 8000 & percent.mt < 7)

# P7
seurat_obj_kb[[6]] <- subset(seurat_obj_kb[[6]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 8)


# P10
seurat_obj_kb[[7]] <- subset(seurat_obj_kb[[7]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 9)

# P14
seurat_obj_kb[[8]] <- subset(seurat_obj_kb[[8]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 13)

# P21
seurat_obj_kb[[9]] <- subset(seurat_obj_kb[[9]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 10)

# Adult
seurat_obj_kb[[10]] <- subset(seurat_obj_kb[[10]],
                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < 12)


# Subset data
for (i in 1:length(seurat_obj_kb)){

  # # Filter out percent mitochondrial genes above the 99.9th percentile
  # max.mito <- quantile(seurat_obj_kb[[i]]@meta.data[["percent.mt"]],probs = .995)
  # 
  # 
  # ## Filter cells
  # seurat_obj_kb[[i]] <- subset(seurat_obj_kb[[i]],
  #                             subset = nFeature_RNA > 200 & nCount_RNA < 10000 & percent.mt < max.mito)
  # Print cell counts
  print(paste(timepoints[i],dim(seurat_obj_kb[[i]])[2]))

}

```

# Postfiltering

```{r,fig.width=11}
# Visualize QC metrics as a violin plots
ggarrange(VlnPlot(seurat_obj_kb[[1]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3),
          VlnPlot(seurat_obj_kb[[2]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[3]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3),
          VlnPlot(seurat_obj_kb[[4]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[5]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3),
          VlnPlot(seurat_obj_kb[[6]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[7]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3),
          VlnPlot(seurat_obj_kb[[8]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))

ggarrange(VlnPlot(seurat_obj_kb[[9]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3),
          VlnPlot(seurat_obj_kb[[10]],
                  features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,))
```


